// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: model/structs.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username     string           `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HashPassword string           `protobuf:"bytes,2,opt,name=hash_password,json=hashPassword,proto3" json:"hash_password,omitempty"`
	Posts        []*PostStg       `protobuf:"bytes,3,rep,name=posts,proto3" json:"posts,omitempty"`
	Following    map[string]int32 `protobuf:"bytes,4,rep,name=following,proto3" json:"following,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *UserStg) Reset() {
	*x = UserStg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_structs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStg) ProtoMessage() {}

func (x *UserStg) ProtoReflect() protoreflect.Message {
	mi := &file_model_structs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStg.ProtoReflect.Descriptor instead.
func (*UserStg) Descriptor() ([]byte, []int) {
	return file_model_structs_proto_rawDescGZIP(), []int{0}
}

func (x *UserStg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStg) GetHashPassword() string {
	if x != nil {
		return x.HashPassword
	}
	return ""
}

func (x *UserStg) GetPosts() []*PostStg {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *UserStg) GetFollowing() map[string]int32 {
	if x != nil {
		return x.Following
	}
	return nil
}

type PostStg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PostStg) Reset() {
	*x = PostStg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_structs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostStg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStg) ProtoMessage() {}

func (x *PostStg) ProtoReflect() protoreflect.Message {
	mi := &file_model_structs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStg.ProtoReflect.Descriptor instead.
func (*PostStg) Descriptor() ([]byte, []int) {
	return file_model_structs_proto_rawDescGZIP(), []int{1}
}

func (x *PostStg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostStg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_model_structs_proto protoreflect.FileDescriptor

var file_model_structs_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdf, 0x01, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1e, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x67, 0x52, 0x05, 0x70, 0x6f, 0x73,
	0x74, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x67, 0x2e,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x1a, 0x3c, 0x0a, 0x0e, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x39, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x74, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x61, 0x72, 0x75, 0x64, 0x61, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_structs_proto_rawDescOnce sync.Once
	file_model_structs_proto_rawDescData = file_model_structs_proto_rawDesc
)

func file_model_structs_proto_rawDescGZIP() []byte {
	file_model_structs_proto_rawDescOnce.Do(func() {
		file_model_structs_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_structs_proto_rawDescData)
	})
	return file_model_structs_proto_rawDescData
}

var file_model_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_structs_proto_goTypes = []interface{}{
	(*UserStg)(nil), // 0: UserStg
	(*PostStg)(nil), // 1: PostStg
	nil,             // 2: UserStg.FollowingEntry
}
var file_model_structs_proto_depIdxs = []int32{
	1, // 0: UserStg.posts:type_name -> PostStg
	2, // 1: UserStg.following:type_name -> UserStg.FollowingEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_structs_proto_init() }
func file_model_structs_proto_init() {
	if File_model_structs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_structs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_structs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostStg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_structs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_structs_proto_goTypes,
		DependencyIndexes: file_model_structs_proto_depIdxs,
		MessageInfos:      file_model_structs_proto_msgTypes,
	}.Build()
	File_model_structs_proto = out.File
	file_model_structs_proto_rawDesc = nil
	file_model_structs_proto_goTypes = nil
	file_model_structs_proto_depIdxs = nil
}
